import type { Metadata } from "next";
import { Varela } from "next/font/google";
import "./globals.css";

import Navbar from "@/components/sections/navbar";

const varela = Varela({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-varela",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${varela.variable} antialiased`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
